version: 1

accepted_iatas:
  - HEL
  - JOE
  - KOK
  - OUL
  - RVN
  - SJY
  - TKU
  - TLL
  - TMP

# Observer options, keyed by 64-character hexadecimal public key.
observers: {}

# Example options:
# observers:
#   "<64-character-public-key>":
#     blacklist: true
#   "<another-64-character-public-key>":
#     override_iata: RVN
